### ISSUE TITLE
Touching the fairies 

### ISSUE THREAD

**Issue by frare241** [Tune389/Tap-Titans-2-Progress-Bot#40] opened 2017-11-04 23:47 UTC
Hello, my problem is when the bot hits the fairies, I even changed the random range to the bottom and closed the egg collection  but also didn't help

**Comment by jayrc** [comment] 2017-11-28 17:42
https://github.com/Tune389/Tap-Titans-2-Progress-Bot/issues/32

The issue is resolved in that thread:
"Click the "No Thanks" button when a fairy ad screen comes up.
You can add this code to the RANDOM ATTACK section in between the "Equipment Stacking" and the Touch.

   var #noThanksColor 0
   getColor #noThanksColor 134 620
   if #noThanksColor == 688378
          touchDown 0 134 620
          sleep #btnDelay
          #time = #time + #btnDelay
          touchUp 0
          sleep #btnDelay
          #time = #time + #btnDelay
   endif
"

**Comment by eljano** [comment] 2017-12-01 08:58
thanks for help.
For me it's good but I see a big slow since I put this. 
It is normaly?
can you explane were we must add the script?
Thanks and sorry for my english ( I m french)

**Comment by zalupakiss** [comment] 2017-12-01 13:41
Instead, change the value of var #focusMainHero 1 to var #focusMainHero 0.
It helped me.
**Let me know if this helped you.**

**Comment by eljano** [comment] 2017-12-01 14:11
it's the same think. Before add the little script for the fairies it was good.
It(s since I add it was slowly

**Comment by jayrc** [comment] 2017-12-03 17:06
RANDOM ATTACK section in between the "Equipment Stacking" and the Touch.

VERY Bottom of the script:

From:
// ----------- RANDOM ATTACK
:randomTouch
	rand #randomX 60 415
	rand #randomY 160 420

	//equipment stacking
	if #randomX > 280 and #randomX < 430 and #randomY > 300
		goto :randomTouch
	endif
	
	//prevent hero story window
	if #randomY > 184 and #randomY < 233 and #randomX > 403
		goto :randomTouch
	endif
	
	if #enableTapping == 1
		touchDown 0 #randomX #randomY
		touchUp 0
	endif
	sleep #hitDelay
	#time = #time + #hitDelay
goto :start

to:

// ----------- RANDOM ATTACK
:randomTouch
	rand #randomX 60 415
	rand #randomY 160 420

	//equipment stacking
	if #randomX > 280 and #randomX < 430 and #randomY > 300
		goto :randomTouch
	endif
	
	//No Thanks to Fairies Popups
	var #noThanksColor 0
	getColor #noThanksColor 134 620
	if #noThanksColor == 688378
	touchDown 0 134 620
	sleep #btnDelay
	#time = #time + #btnDelay
	touchUp 0
	sleep #btnDelay
	#time = #time + #btnDelay
	endif
		
	//prevent hero story window
	if #randomY > 184 and #randomY < 233 and #randomX > 403
		goto :randomTouch
	endif
	
	if #enableTapping == 1
		touchDown 0 #randomX #randomY
		touchUp 0
	endif
	sleep #hitDelay
	#time = #time + #hitDelay
goto :start

**Comment by eljano** [comment] 2017-12-04 11:58
thank you very much

**Comment by jayrc** [comment] 2017-12-06 17:57
Absolutely! Please close this, as it is resolved.

**Closed** 2017-12-13 19:19 UTC
